export enum AdStatus {
  DRAFT = 'DRAFT',
  FOR_REVIEW = 'FOR_REVIEW',

  REJECTED = 'REJECTED',
  HOLD = 'HOLD',
  YET_TO_BE_PUBLISHED = 'YET_TO_BE_PUBLISHED',
  PUBLISHED = 'PUBLISHED',
  PAUSED = 'PAUSED',
}
